import formsPlugin from '@tailwindcss/forms'
import containerQueriesPlugin from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#004395',
        'tertiary-fixed-dim': '#ffb95f',
        'secondary-fixed': '#6ffbbe',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#35609e',
        'tertiary-container': '#f5a623',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary-container': '#3e2400',
        'secondary-container': '#00a572',
        'secondary-fixed-dim': '#4edea3',
        'surface-dim': '#d9dce3',
        'inverse-on-surface': '#f0f1f5',
        'on-surface-variant': '#4f5665',
        outline: '#737b8c',
        tertiary: '#9a5b00',
        'surface-bright': '#ffffff',
        background: '#f8f9fc',
        'primary-fixed': '#d8e2ff',
        'on-secondary-container': '#00311f',
        'on-tertiary-fixed': '#2a1700',
        primary: '#35609e',
        'on-error': '#ffffff',
        'inverse-primary': '#b3caff',
        'on-error-container': '#6e0a12',
        'on-tertiary-fixed-variant': '#653e00',
        'error-container': '#ffd9dc',
        'primary-container': '#b3caff',
        'on-secondary': '#ffffff',
        'surface-container': '#eef0f5',
        'inverse-surface': '#2d3038',
        'on-secondary-fixed': '#002113',
        'on-primary': '#ffffff',
        'surface-container-high': '#e5e8ef',
        'outline-variant': '#424754',
        'surface-container-low': '#1c1b1c',
        'on-primary-fixed': '#001a42',
        'on-tertiary': '#472a00',
        'tertiary-fixed': '#ffddb8',
        'surface-variant': '#dfe2e9',
        'primary-fixed-dim': '#9bb9f0',
        'on-background': '#1b1d24',
        secondary: '#16805c',
        'on-primary-container': '#00285d',
        'surface-container-highest': '#dce0e8',
        surface: '#ffffff',
        error: '#ba1a25',
        'on-surface': '#1b1d24',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        margin: '32px',
        gutter: '20px',
        md: '24px',
        lg: '40px',
        base: '4px',
        xl: '64px',
        sm: '16px',
        xs: '8px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'mono-data': ['Geist Mono', 'monospace'],
        'display-lg': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'mono-data': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '600' }],
      },
    },
  },
  plugins: [formsPlugin, containerQueriesPlugin],
}
