import formsPlugin from '@tailwindcss/forms'
import containerQueriesPlugin from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#004395',
        'tertiary-fixed-dim': '#ffb95f',
        'secondary-fixed': '#6ffbbe',
        'surface-container-lowest': '#0e0e0f',
        'surface-tint': '#adc6ff',
        'tertiary-container': '#ca8100',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary-container': '#3e2400',
        'secondary-container': '#00a572',
        'secondary-fixed-dim': '#4edea3',
        'surface-dim': '#131314',
        'inverse-on-surface': '#313031',
        'on-surface-variant': '#c2c6d6',
        outline: '#8c909f',
        tertiary: '#ffb95f',
        'surface-bright': '#3a393a',
        background: '#131314',
        'primary-fixed': '#d8e2ff',
        'on-secondary-container': '#00311f',
        'on-tertiary-fixed': '#2a1700',
        primary: '#adc6ff',
        'on-error': '#690005',
        'inverse-primary': '#005ac2',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#653e00',
        'error-container': '#93000a',
        'primary-container': '#4d8eff',
        'on-secondary': '#003824',
        'surface-container': '#201f20',
        'inverse-surface': '#e5e2e3',
        'on-secondary-fixed': '#002113',
        'on-primary': '#002e6a',
        'surface-container-high': '#2a2a2b',
        'outline-variant': '#424754',
        'surface-container-low': '#1c1b1c',
        'on-primary-fixed': '#001a42',
        'on-tertiary': '#472a00',
        'tertiary-fixed': '#ffddb8',
        'surface-variant': '#353436',
        'primary-fixed-dim': '#adc6ff',
        'on-background': '#e5e2e3',
        secondary: '#4edea3',
        'on-primary-container': '#00285d',
        'surface-container-highest': '#353436',
        surface: '#131314',
        error: '#ffb4ab',
        'on-surface': '#e5e2e3',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        margin: '32px',
        gutter: '20px',
        md: '24px',
        lg: '40px',
        base: '4px',
        xl: '64px',
        sm: '16px',
        xs: '8px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'mono-data': ['Geist Mono', 'monospace'],
        'display-lg': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'mono-data': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '600' }],
      },
    },
  },
  plugins: [formsPlugin, containerQueriesPlugin],
}
